# others/deny.toml
[advisories]
# crates.io のセキュリティアドバイザリをチェック
vulnerability = "deny" # 見つけたらエラーにする

[bans]
# 二重依存やバージョン違いを禁止
multiple-versions = "warn"

[sources]
# crates.io以外のソースを禁止する
unknown-registry = "deny"
unknown-git = "deny"
