name: Cargo Deny

on:
  push:
  pull_request:

jobs:
  cargo-deny:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        project:
          - name: dictsqlite_v2
            path: ./dictsqlite_v2/dictsqlite
          - name: dictsqlite_v4.1
            path: ./others/beta-versions/dictsqlite_v4.1
    steps:
      - uses: actions/checkout@v4

      - uses: EmbarkStudios/cargo-deny-action@v2
        with:
          log-level: warn
          manifest-path: ${{ matrix.project.path }}/Cargo.toml
          command: check advisories bans licenses sources
          arguments: --all-features
